### PR TITLE
refactor code

### PR DESCRIPTION
**Pull request by jensheerin**
Updates for better readability with docs and modification to terraform token changes

### CODE REVIEW

**Comment by grayzu** [comment]
@jensheerin Please run terraform fmt to format the files consistently. Otherwize, this looks good to me.

**Comment by jensheerin** [comment]
@grayzu Format completed. Thank you!

**Comment by jensheerin** [comment]
sign-off

**Comment by grayzu** [comment]
Thanks Jen! LGTM.

**Pull request merged**
