### PR TITLE
User Story 1871520 (Code)

### PR DESCRIPTION
**Pull request by TomArcherMsft**
User Story: https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1871520

### CODE REVIEW

**Review by grayzu — CHANGES_REQUESTED** [review]
In general, this PR looks great. Please run this through terraform fmt to clean up the code a bit and then it should be good to go.

**Comment by TomArcherMsft** [comment]
@grayzu Thanks, Mark! I've formatted the code and everything should be ready to be merged. Per our template, I'll also send email to tfaztri.

**Review by grayzu — COMMENTED** [review]
LGTM

Although, it would be good to have more comments in the *.tf files, especially if this is going to be included in our docs, we can update that later.

**Comment by TomArcherMsft** [comment]
@grayzu Thanks. Could you merge this so I can publish the article today?

**Review by grayzu — APPROVED** [review]

**Pull request merged**
