### PR TITLE
User Story 124432

### PR DESCRIPTION
**Pull request by TomArcherMsft**
[User Story 124432](https://dev.azure.com/msft-skilling/Content/_workitems/edit/124432)

### CODE REVIEW

**Review by lonegunmanb — COMMENTED** [review]
I have one question for using `Microsoft.Compute/sshPublicKeys@2022-11-01` to generate ssh key @TomArcherMsft, how can we get the corresponding private key if we'd like to connect to the vm via ssh?

**Comment by TomArcherMsft** [comment]
> I have one question for using `Microsoft.Compute/sshPublicKeys@2022-11-01` to generate ssh key @TomArcherMsft, how can we get the corresponding private key if we'd like to connect to the vm via ssh?

I don't know. @grayzu?

**Review by grayzu — APPROVED** [review]
LGTM

**Review by lonegunmanb — APPROVED** [review]
LGTM!

**Pull request merged**
