### PR TITLE
Added new folder to create azure container app

### PR DESCRIPTION
**Pull request by ravick4u**

### CODE REVIEW

**Comment by ravick4u** [comment]
@microsoft-github-policy-service agree

**Comment by ravick4u** [comment]
Sorry to bother @TomArcherMsft . I was wondering if I have any action item on this PR, if yes could you please let me know what it is.

**Comment by TomArcherMsft** [comment]
@ravick4u Apologies for the delay. I'm currently out of the office and will look the PR over when I return next Monday. Thanks much for your contribution!

**Comment by ravick4u** [comment]
@TomArcherMsft Thanks for the response while you are out of office.

**Comment by TomArcherMsft** [comment]
@ravick4u We have a specific format for samples that the product group requires. We also have a tool that creates the required files using the required format. Therefore, when I return (next Tuesday), I'm going to take your files and run them through our tool   to create a new PR. Since the repo I'll be using is an internal repo that you do not have visibility into, I'll keep this PR open and communicate with you via this PR so that you're kept up to date.

**Comment by TomArcherMsft** [comment]
@ravick4u FYI, I'm back in the office today and submitting the PR for our product group's review. Thanks much for your patience.

**Comment by ravick4u** [comment]
Thanks for the update @TomArcherMsft

**Review by lonegunmanb — COMMENTED** [review]
Thanks @ravick4u for opening this pr! LGTM!

**Pull request merged**
