### PR TITLE
Samples/compliance testing

### PR DESCRIPTION
**Pull request by aheumaier**

### CODE REVIEW

**Comment by aheumaier** [comment]
@jcorioland  can you take a look here

**Review by jcorioland — COMMENTED** [review]
Hey @aheumaier Not sure why you added the header, prerequesites, and next steps in this file, as it is the sample and not the documentation. This is not required. Can you remove it? Thanks!

**Comment by aheumaier** [comment]
> Hey @aheumaier Not sure why you added the header, prerequesites, and next steps in this file, as it is the sample and not the documentation. This is not required. Can you remove it? Thanks!

Resolved

**Review by jcorioland — APPROVED** [review]
LGTM. Thanks @aheumaier !

**Pull request merged**
