### PR TITLE
fix link in storage account with static website

### PR DESCRIPTION
**Pull request by ravick4u**
The link on the repo is incorrect so creating this PR to fix the link

### CODE REVIEW

**Comment by TomArcherMsft** [comment]
@ravick4u Thanks for the feedback! #sign-off

**Comment by ravick4u** [comment]
@TomArcherMsft Because this is my first PR would like to know if I am supposed to do anything now or I am all set?

**Comment by TomArcherMsft** [comment]
@ravick4u You don't need to do anything at this point. An admin from that repo needs to evaluate and merge the PR.
cc: @grayzu @stemaMSFT @lonegunmanb

**Comment by stemaMSFT** [comment]
LGTM! Merged.

**Pull request merged**
