### PR TITLE
New Sample for iothub with private link

### PR DESCRIPTION
**Pull request by abeebu**
This PR adds a new quickstart sample for deploying iothub with device provisioning service behind a virtual network

### CODE REVIEW

**Comment by abeebu** [comment]
@lonegunmanb Would you be able to review this PR please?

**Comment by lonegunmanb** [comment]
> @lonegunmanb Would you be able to review this PR please?

Hi @abeebu thanks for opening this pr! Overall it LGTM but I found that you've created a private dns zone for event hub, but no resource for event hub, no `azurerm_eventhub`, no private endpoint or private link for eventhub. Is that correct?

**Comment by abeebu** [comment]
> > @lonegunmanb Would you be able to review this PR please?
> 
> Hi @abeebu thanks for opening this pr! Overall it LGTM but I found that you've created a private dns zone for event hub, but no resource for event hub, no `azurerm_eventhub`, no private endpoint or private link for eventhub. Is that correct?

@lonegunmanb yes, this configuration utilizes the built-in eventhub endpoint for iothub. So we(the customer) does not need to deploy a separate eventhub resource. However to ensure private connectivity between the iothub and its builtin endpoint, we need to add the private dns zone and create a dns record for its IP.

See [here](https://learn.microsoft.com/en-us/azure/iot-hub/virtual-network-support#built-in-event-hubs-compatible-endpoint) for more details on the builtin endpoint.

In a follow up PR later this month, I will also show the configuration for deploying the iothub together with a separate storage resource and eventhub resource for message routing all behind a VNET.

**Comment by abeebu** [comment]
Just a nudge that this PR is awaiting your action @lonegunmanb 😁

**Comment by abeebu** [comment]
Tagging you @stemaMSFT and @TomArcherMsft 🙂

**Comment by TomArcherMsft** [comment]
@abeebu Thanks much for the contribution.

If you haven't done so already, please read the Contributor Guide article, "[Publish a Terraform Quickstart](https://review.learn.microsoft.com/en-us/help/contribute/global-terraform-template?branch=main#create-and-publish-the-terraform-sample)".

1. **[main.tf]** Please utilize the pattern required by the PG for the rg name. You can look at the [following code](https://github.com/Azure/terraform/blob/master/quickstart/101-resource-group/main.tf) for an example.
2. **[providers.tf]** You currently have a provider version constraint of: `>= 3.35.0, < 4.0.0`. I'm assuming you're specifying 3.35 and above but less than 4.0. Is that correct? If so, the canonical way to write that is `~> 3.351`. The [pessimistic constraint operator](https://developer.hashicorp.com/terraform/language/expressions/version-constraints) (the tilde) basically tells Terraform that you want the latest version but only incrementing the right-most version component.
3. **[variables.tf]** Use the pattern for declaring the rg vars as used in the following example: [variables.tf](https://github.com/Azure/terraform/blob/master/quickstart/101-resource-group/variables.tf)
4. **[readme.md]** Use the table format as in https://github.com/Azure/terraform/blob/master/quickstart/101-resource-group/variables.tf
5. **[readme.md]** The first two rows of the table should be the rg prefix and rg location as in https://github.com/Azure/terraform/blob/master/quickstart/101-resource-group/variables.tf
6. @grayzu This PR has both a main.tf and a network.tf. Are you ok with that, or should everything go into main.tf?
7. @abeebu What is the Azure CLI command to display the main resource created with this sample? Are all the params required by the Azure CLI command in the outputs.tf file?
8. @lonegunmanb Could you please review when time permits? I've put it on the kanban board. Thanks!

**Comment by lonegunmanb** [comment]
Apology for the late reply @abeebu & @TomArcherMsft , LGTM!

**Review by lonegunmanb — APPROVED** [review]

**Pull request merged**
