### PR TITLE
User Story 261941 - Fix ssh.tf

### PR DESCRIPTION
**Pull request by TomArcherMsft**
[User Story 261941](https://dev.azure.com/msft-skilling/Content/_workitems/edit/261941)

### CODE REVIEW

**Comment by stemaMSFT** [comment]
@TomArcherMsft this LGTM but there's E2E errors that you'll need to resolve. Afterward @lonegunmanb or someone else can go ahead and merge.

**Comment by TomArcherMsft** [comment]
@stemaMSFT I believe that @lonegunmanb has to resolve the only error as it's a test environment error where an older version of packer is being used: 

```
Test_Quickstarts/quickstart/201-vmss-packer-jumpbox 2024-06-07T21:10:17Z logger.go:66: is 1.11.0. You can update by downloading from www.packer.io/downloads
    quickstart_test.go:137: 
        	Error Trace:	/src/test/e2e/quickstart_test.go:137
        	Error:      	Received unexpected error:
        	            	Malformed version: Packer v1.10.2
        	            	
        	            	Your version of Packer is out of date! The latest version
        	            	is 1.11.0. You can update by downloading from www.packer.io/downloads
        	Test:       	Test_Quickstarts/quickstart/201-vmss-packer-jumpbox
```

**Comment by stemaMSFT** [comment]
@lonegunmanb can we get the fix here rolled out?

**Comment by lonegunmanb** [comment]
I'll fix the test. @TomArcherMsft

**Review by lonegunmanb — APPROVED** [review]
Thanks @TomArcherMsft , LGTM!

**Pull request merged**
